apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opensearch-operator-binding
subjects:
  - kind: ServiceAccount
    name: opensearch-operator-sa
    namespace: opensearch
roleRef:
  kind: ClusterRole
  name: opensearch-operator-role
  apiGroup: rbac.authorization.k8s.io

