apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  general:
    serviceName: opensearch-cluster
    version: 2.7.0
  nodePools:
    - component: nodes
      replicas: 3
      roles:
        - cluster_manager
        - data
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "1000m"
          memory: "4Gi"
      diskSize: "20Gi"
      persistence:
        storageClass: gp2
        accessModes:
          - ReadWriteOnce
  dashboards:
    enable: true
    version: 2.9.0
    replicas: 1
    tls:
      enable: true
      generate: true
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
  security:
    config:
      securityConfigSecret:
        name: ""
    tls:
      transport:
        generate: true
        perNode: true
